apiVersion: v2
name: common
version: 0.1.1
kubeVersion: 1.28.x
description: Chart for deploying common resources used by others Charts.
keywords:
  - Azure Kubernetes
  - Common
  - Namespace
  - Azure Storage Account
maintainers:
  - name: "Samuel A. Luciano L."
    email: "sa.lassis@gmail.com"