resources:
  namespace: "helm-dev"
  groupName: "kubernetes-test"
  storageAccount:
    name: "odoosa"
    key: "p03h3bIqESDwMC9A9Szl8hNPssExbLhT4pvMcxLmIlfhN3lrD2bwSHIOHeW5JvYQeR5asCtatTmM"
environment:
  postgres:
    persistentVolume:
      name: "accounterprise-ce-postgres-data-pv"
      storageCapacity: "2Gi"
      nfsFileShareName: "postgres-data-fs"
    persistentVolumeClaim:
      name: "accounterprise-ce-postgres-data-pvc"
    deployment:
      name: "accounterprise-ce-postgres-deployment"
      replicas: "1"
      container:
        name: "postgres"
        imageName: "postgres"
        imageTag: "16"
        limits:
          memory: "256Mi"
          cpu: "100m"
        variables:
          postgresUser: "usr_odoo"
          postgresPassword: "Q37zfHgsswMnYQnKPZG4XQ5p"
          postgresDataDirectory: "/var/lib/postgresql/accounterprise-ce/"
    service:
      name: "accounterprise-ce-postgres-service"
      port: "15401"
  odoo:
    configMap:
      name: "accounterprise-ce-odoo-config-cm"
      databaseName: "accounterprise-ce"
    persistentVolume:
      name: "accounterprise-ce-odoo-data-pv"
      storageCapacity: "5Gi"
      nfsFileShareName: "odoo-data-fs"
    persistentVolumeClaim:
      name: "accounterprise-ce-odoo-data-pvc"
    deployment:
      name: "accounterprise-ce-odoo-deployment"
      replicas: "1"
      container:
        name: "postgres"
        imageName: "postgres"
        imageTag: "16"
        limits:
          memory: "512Mi"
          cpu: "200m"
        variables:
          postgresUser: "usr_odoo"
          postgresPassword: "Q37zfHgsswMnYQnKPZG4XQ5p"
          postgresDataDirectory: "/var/lib/postgresql/accounterprise-ce/"
    service:
      name: "accounterprise-ce-odoo-service"
      port: "19801"
      geventPort: "20801"
    ingress:
      name: "accounterprise-ce-odoo-ingress"
      className: "webapprouting.kubernetes.azure.com"
      host: "odoo-dev-ce-az.accounterprise.com"
      tls:
        secretName: "keyvault-accounterprise-ce"