resources:
  namespace: "helm-dev"
  groupName: "kubernetes-test"
  storageAccount:
    name: "odoosa"
    key: "KEY/TOKEN/PASSWORD TO ACCESS AZURE STORAGE ACCOUNT"
environment:
  prefix: "accounterprise-ce"
  postgres:
    persistentVolume:
      name: "postgres-data-pv"
      storageCapacity: "2Gi"
      nfsFileShareName: "postgres-data-fs"
    persistentVolumeClaim:
      name: "postgres-data-pvc"
    deployment:
      name: "postgres-deployment"
      replicas: "1"
      container:
        name: "postgres"
        imageName: "postgres"
        imageTag: "16"
        privateRepository: 
          secretName: "postgres-private-repository-secret"
          dockerUserName: ""
          dockerUserPassword: ""
          dockerUserEmail: ""
        isPrivateRepository: "false"
        limits:
          memory: "256Mi"
          cpu: "100m"
        variables:
          postgresUser: "usr_odoo"
          postgresPassword: "Q37zfHgsswMnYQnKPZG4XQ5p"
          postgresDataDirectory: "/var/lib/postgresql"
    service:
      name: "postgres-service"
      port: "15401"
  odoo:
    edition: "ce"
    appEnvironment: "prod"
    maxRetries: 3
    sleepTime: 10
    modulesToInstall: "base,billing_do,professional_templates"
    configMap:
      name: "odoo-config-cm"
    persistentVolume:
      name: "odoo-data-pv"
      storageCapacity: "5Gi"
      nfsFileShareName: "odoo-data-fs"
    persistentVolumeClaim:
      name: "odoo-data-pvc"
    deployment:
      name: "odoo-deployment"
      replicas: "1"
      container:
        name: "odoo"
        imageName: "odoo"
        imageTag: "16.0"
        privateRepository: 
          secretName: "odoo-private-repository-secret"
          dockerUserName: ""
          dockerUserPassword: ""
          dockerUserEmail: ""
        isPrivateRepository: "false"
        requests:
          memory: "512Mi"
          cpu: "150m"
        limits:
          memory: "790Mi"
          cpu: "240m"
    service:
      name: "odoo-service"
      port: "19801"
      geventPort: "20801"
    ingress:
      name: "odoo-ingress"
      className: "webapprouting.kubernetes.azure.com"
      host: "odoo-dev-ce-az.accounterprise.com"
      tls:
        secretName: "tls-certificate"
      proxyReadTimeout: "3200"
      proxyConnectTimeout: "180"
      proxySendTimeout: "180"
      clientMaxBodySize: "256m"